//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekendTaskMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BemaxEntities : DbContext
    {
        public BemaxEntities()
            : base("name=BemaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Advisor> Advisors { get; set; }
        public virtual DbSet<OurWork> OurWorks { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Choos> Chooses { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Tester> Testers { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
    }
}
